DROP VIEW IF EXISTS dochead;
CREATE VIEW dochead AS
SELECT 'Q' AS dochead_type,
       quhead_id AS dochead_id,
       quhead_number AS dochead_number,
       NULL AS dochead_ordernumber,
       quhead_cust_id AS dochead_cust_id,
       NULL::INTEGER AS dochead_vend_id,
       quhead_curr_id AS dochead_curr_id,
       quhead_quotedate AS dochead_date,
       NULL::TEXT AS dochead_origtype,
       NULL::INTEGER AS dochead_origid,
       NULL::DATE AS dochead_origdate,
       NULL::TEXT AS dochead_orignumber,
       quhead_taxzone_id AS dochead_taxzone_id,
       quhead_warehous_id AS dochead_warehous_id,
       quhead_shipvia AS dochead_shipvia,
       quhead_shipto_id AS dochead_shipto_id,
       quhead_shiptoaddress1 AS dochead_toaddr1,
       quhead_shiptoaddress2 AS dochead_toaddr2,
       quhead_shiptoaddress3 AS dochead_toaddr3,
       quhead_shiptocity AS dochead_tocity,
       quhead_shiptostate AS dochead_tostate,
       quhead_shiptozipcode AS dochead_tozip,
       quhead_shiptocountry AS dochead_tocountry,
       quhead_freight AS dochead_freight,
       quhead_misc AS dochead_misc,
       quhead_misc_descrip AS dochead_misc_descrip,
       quhead_freight_taxtype_id AS dochead_freight_taxtype_id,
       quhead_misc_taxtype_id AS dochead_misc_taxtype_id,
       quhead_misc_discount AS dochead_misc_discount,
       quhead_tax_exemption AS dochead_tax_exemption
  FROM quhead
UNION ALL
SELECT 'S',
       cohead_id,
       cohead_number,
       NULL,
       cohead_cust_id,
       NULL,
       cohead_curr_id,
       cohead_orderdate,
       NULL,
       NULL,
       NULL,
       NULL,
       cohead_taxzone_id,
       cohead_warehous_id,
       cohead_shipvia,
       cohead_shipto_id,
       cohead_shiptoaddress1,
       cohead_shiptoaddress2,
       cohead_shiptoaddress3,
       cohead_shiptocity,
       cohead_shiptostate,
       cohead_shiptozipcode,
       cohead_shiptocountry,
       cohead_freight,
       cohead_misc,
       cohead_misc_descrip,
       cohead_freight_taxtype_id,
       cohead_misc_taxtype_id,
       cohead_misc_discount,
       cohead_tax_exemption
  FROM cohead
UNION ALL
SELECT 'COB',
       cobmisc_id,
       cohead_number,
       NULL,
       cohead_cust_id,
       NULL,
       cohead_curr_id,
       cohead_orderdate,
       NULL,
       NULL,
       NULL,
       NULL,
       cobmisc_taxzone_id,
       cohead_warehous_id,
       cobmisc_shipvia,
       cohead_shipto_id,
       cohead_shiptoaddress1,
       cohead_shiptoaddress2,
       cohead_shiptoaddress3,
       cohead_shiptocity,
       cohead_shiptostate,
       cohead_shiptozipcode,
       cohead_shiptocountry,
       cobmisc_freight,
       cobmisc_misc,
       cobmisc_misc_descrip,
       cobmisc_freight_taxtype_id,
       cobmisc_misc_taxtype_id,
       cobmisc_misc_discount,
       cobmisc_tax_exemption
  FROM cobmisc
  JOIN cohead ON cobmisc_cohead_id = cohead_id
UNION ALL
SELECT 'INV',
       invchead_id,
       invchead_invcnumber,
       invchead_ordernumber,
       invchead_cust_id,
       NULL,
       invchead_curr_id,
       invchead_invcdate,
       NULL,
       NULL,
       NULL,
       NULL,
       invchead_taxzone_id,
       invchead_warehous_id,
       invchead_shipvia,
       invchead_shipto_id,
       invchead_shipto_address1,
       invchead_shipto_address2,
       invchead_shipto_address3,
       invchead_shipto_city,
       invchead_shipto_state,
       invchead_shipto_zipcode,
       invchead_shipto_country,
       invchead_freight,
       invchead_misc_amount,
       invchead_misc_descrip,
       invchead_freight_taxtype_id,
       invchead_misc_taxtype_id,
       invchead_misc_discount,
       invchead_tax_exemption
  FROM invchead
UNION ALL
SELECT 'P',
       pohead_id,
       pohead_number,
       NULL,
       NULL,
       pohead_vend_id,
       pohead_curr_id,
       pohead_orderdate,
       NULL,
       NULL,
       NULL,
       NULL,
       pohead_taxzone_id,
       pohead_warehous_id,
       pohead_shipvia,
       NULL,
       pohead_vendaddress1,
       pohead_vendaddress2,
       pohead_vendaddress3,
       pohead_vendcity,
       pohead_vendstate,
       pohead_vendzipcode,
       pohead_vendcountry,
       pohead_freight,
       0.0,
       NULL,
       pohead_freight_taxtype_id,
       NULL,
       FALSE,
       pohead_tax_exemption
  FROM pohead
UNION ALL
SELECT 'VCH',
       vohead_id,
       vohead_number,
       pohead_number,
       NULL,
       vohead_vend_id,
       vohead_curr_id,
       vohead_docdate,
       NULL,
       NULL,
       NULL,
       NULL,
       vohead_taxzone_id,
       COALESCE(pohead_warehous_id, warehous_id),
       pohead_shipvia,
       NULL,
       COALESCE(pohead_vendaddress1, addr_line1),
       COALESCE(pohead_vendaddress2, addr_line2),
       COALESCE(pohead_vendaddress3, addr_line3),
       COALESCE(pohead_vendcity, addr_city),
       COALESCE(pohead_vendstate, addr_state),
       COALESCE(pohead_vendzipcode, addr_postalcode),
       COALESCE(pohead_vendcountry, addr_country),
       vohead_freight,
       0.0,
       NULL,
       vohead_freight_taxtype_id,
       NULL,
       FALSE,
       vohead_tax_exemption
  FROM vohead
  LEFT OUTER JOIN pohead ON vohead_pohead_id = pohead_id
  LEFT OUTER JOIN whsinfo ON COALESCE(vohead_pohead_id, -1) = -1
                         AND (SELECT vodist_warehous_id
                                FROM vodist
                               WHERE vodist_vohead_id = vohead_id
                               ORDER BY vodist_id
                               LIMIT 1) =
                             warehous_id
  LEFT OUTER JOIN addr ON warehous_addr_id = addr_id
UNION ALL
SELECT 'CM',
       cmhead_id,
       cmhead_number,
       NULL,
       cmhead_cust_id,
       NULL,
       cmhead_curr_id,
       cmhead_docdate,
       CASE WHEN invchead_id IS NOT NULL THEN 'INV' END,
       invchead_id,
       invchead_invcdate,
       'INV-' || invchead_invcnumber,
       cmhead_taxzone_id,
       COALESCE(invchead_warehous_id, cmhead_warehous_id),
       COALESCE(invchead_shipvia, cmhead_shipvia),
       cmhead_shipto_id,
       COALESCE(invchead_shipto_address1, cmhead_shipto_address1),
       COALESCE(invchead_shipto_address2, cmhead_shipto_address2),
       COALESCE(invchead_shipto_address3, cmhead_shipto_address3),
       COALESCE(invchead_shipto_city, cmhead_shipto_city),
       COALESCE(invchead_shipto_state, cmhead_shipto_state),
       COALESCE(invchead_shipto_zipcode, cmhead_shipto_zipcode),
       COALESCE(invchead_shipto_country, cmhead_shipto_country),
       cmhead_freight,
       cmhead_misc,
       cmhead_misc_descrip,
       COALESCE(invchead_freight_taxtype_id, cmhead_freight_taxtype_id),
       COALESCE(invchead_misc_taxtype_id, cmhead_misc_taxtype_id),
       cmhead_misc_discount,
       cmhead_tax_exemption
  FROM cmhead
  LEFT OUTER JOIN invchead ON cmhead_invcnumber = invchead_invcnumber
UNION ALL
SELECT 'AR',
       aropen_id,
       aropen_docnumber,
       NULL,
       aropen_cust_id,
       NULL,
       aropen_curr_id,
       aropen_docdate,
       NULL,
       NULL,
       NULL,
       NULL,
       aropen_taxzone_id,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       0.0,
       0.0,
       NULL,
       NULL,
       NULL,
       FALSE,
       NULL
  FROM aropen
UNION ALL
SELECT 'AP',
       apopen_id,
       apopen_docnumber,
       NULL,
       NULL,
       apopen_vend_id,
       apopen_curr_id,
       apopen_docdate,
       NULL,
       NULL,
       NULL,
       NULL,
       apopen_taxzone_id,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       0.0,
       0.0,
       NULL,
       NULL,
       NULL,
       FALSE,
       NULL
  FROM apopen
UNION ALL
SELECT 'CK',
       checkhead_id,
       checkhead_number::TEXT,
       NULL,
       CASE WHEN checkhead_recip_type = 'C' THEN checkhead_recip_id END,
       CASE WHEN checkhead_recip_type = 'V' THEN checkhead_recip_id END,
       checkhead_curr_id,
       checkhead_checkdate,
       NULL,
       NULL,
       NULL,
       NULL,
       checkhead_taxzone_id,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       0.0,
       0.0,
       NULL,
       NULL,
       NULL,
       FALSE,
       NULL
  FROM checkhead
UNION ALL
SELECT 'CR',
       cashrcpt_id,
       cashrcpt_number,
       NULL,
       cashrcpt_cust_id,
       NULL,
       cashrcpt_curr_id,
       cashrcpt_distdate,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       NULL,
       0.0,
       0.0,
       NULL,
       NULL,
       NULL,
       FALSE,
       NULL
  FROM cashrcpt;
