DROP VIEW IF EXISTS dochead;
CREATE VIEW dochead AS
SELECT 'Q' AS dochead_type,
       quhead_id AS dochead_id,
       quhead_number AS dochead_number,
       quhead_cust_id AS dochead_cust_id,
       quhead_curr_id AS dochead_curr_id,
       quhead_quotedate AS dochead_date,
       quhead_taxzone_id AS dochead_taxzone_id,
       quhead_warehous_id AS dochead_warehous_id,
       quhead_shipvia AS dochead_shipvia,
       quhead_shipto_id AS dochead_shipto_id,
       quhead_shiptoaddress1 AS dochead_toaddr1,
       quhead_shiptoaddress2 AS dochead_toaddr2,
       quhead_shiptoaddress3 AS dochead_toaddr3,
       quhead_shiptocity AS dochead_tocity,
       quhead_shiptostate AS dochead_tostate,
       quhead_shiptozipcode AS dochead_tozip,
       quhead_shiptocountry AS dochead_tocountry,
       quhead_freight AS dochead_freight,
       quhead_misc AS dochead_misc,
       quhead_freight_taxtype_id AS dochead_freight_taxtype_id,
       quhead_misc_taxtype_id AS dochead_misc_taxtype_id,
       quhead_misc_discount AS dochead_misc_discount
  FROM quhead
UNION ALL
SELECT 'S',
       cohead_id,
       cohead_number,
       cohead_cust_id,
       cohead_curr_id,
       cohead_orderdate,
       cohead_taxzone_id,
       cohead_warehous_id,
       cohead_shipvia,
       cohead_shipto_id,
       cohead_shiptoaddress1,
       cohead_shiptoaddress2,
       cohead_shiptoaddress3,
       cohead_shiptocity,
       cohead_shiptostate,
       cohead_shiptozipcode,
       cohead_shiptocountry,
       cohead_freight,
       cohead_misc,
       cohead_freight_taxtype_id,
       cohead_misc_taxtype_id,
       cohead_misc_discount
  FROM cohead
UNION ALL
SELECT 'COB',
       cobmisc_id,
       cohead_number,
       cohead_cust_id,
       cohead_curr_id,
       cohead_orderdate,
       cobmisc_taxzone_id,
       cohead_warehous_id,
       cobmisc_shipvia,
       cohead_shipto_id,
       cohead_shiptoaddress1,
       cohead_shiptoaddress2,
       cohead_shiptoaddress3,
       cohead_shiptocity,
       cohead_shiptostate,
       cohead_shiptozipcode,
       cohead_shiptocountry,
       cobmisc_freight,
       cobmisc_misc,
       cobmisc_freight_taxtype_id,
       cobmisc_misc_taxtype_id,
       cobmisc_misc_discount
  FROM cobmisc
  JOIN cohead ON cobmisc_cohead_id = cohead_id
UNION ALL
SELECT 'INV',
       invchead_id,
       invchead_invcnumber,
       invchead_cust_id,
       invchead_curr_id,
       invchead_invcdate,
       invchead_taxzone_id,
       invchead_warehous_id,
       invchead_shipvia,
       invchead_shipto_id,
       invchead_shipto_address1,
       invchead_shipto_address2,
       invchead_shipto_address3,
       invchead_shipto_city,
       invchead_shipto_state,
       invchead_shipto_zipcode,
       invchead_shipto_country,
       invchead_freight,
       invchead_misc_amount,
       invchead_freight_taxtype_id,
       invchead_misc_taxtype_id,
       invchead_misc_discount
  FROM invchead;
