DROP VIEW IF EXISTS dochead;
CREATE VIEW dochead AS
SELECT 'Q' AS dochead_type,
       quhead_id AS dochead_id,
       quhead_number AS dochead_number,
       quhead_cust_id AS dochead_cust_id,
       NULL::INTEGER AS dochead_vend_id,
       quhead_curr_id AS dochead_curr_id,
       quhead_quotedate AS dochead_date,
       NULL::DATE AS dochead_origdate,
       NULL::TEXT AS dochead_origorder,
       quhead_taxzone_id AS dochead_taxzone_id,
       quhead_warehous_id AS dochead_warehous_id,
       quhead_shipvia AS dochead_shipvia,
       quhead_shipto_id AS dochead_shipto_id,
       quhead_shiptoaddress1 AS dochead_toaddr1,
       quhead_shiptoaddress2 AS dochead_toaddr2,
       quhead_shiptoaddress3 AS dochead_toaddr3,
       quhead_shiptocity AS dochead_tocity,
       quhead_shiptostate AS dochead_tostate,
       quhead_shiptozipcode AS dochead_tozip,
       quhead_shiptocountry AS dochead_tocountry,
       quhead_freight AS dochead_freight,
       quhead_misc AS dochead_misc,
       quhead_freight_taxtype_id AS dochead_freight_taxtype_id,
       quhead_misc_taxtype_id AS dochead_misc_taxtype_id,
       quhead_misc_discount AS dochead_misc_discount
  FROM quhead
UNION ALL
SELECT 'S',
       cohead_id,
       cohead_number,
       cohead_cust_id,
       NULL,
       cohead_curr_id,
       cohead_orderdate,
       NULL,
       NULL,
       cohead_taxzone_id,
       cohead_warehous_id,
       cohead_shipvia,
       cohead_shipto_id,
       cohead_shiptoaddress1,
       cohead_shiptoaddress2,
       cohead_shiptoaddress3,
       cohead_shiptocity,
       cohead_shiptostate,
       cohead_shiptozipcode,
       cohead_shiptocountry,
       cohead_freight,
       cohead_misc,
       cohead_freight_taxtype_id,
       cohead_misc_taxtype_id,
       cohead_misc_discount
  FROM cohead
UNION ALL
SELECT 'COB',
       cobmisc_id,
       cohead_number,
       cohead_cust_id,
       NULL,
       cohead_curr_id,
       cohead_orderdate,
       NULL,
       NULL,
       cobmisc_taxzone_id,
       cohead_warehous_id,
       cobmisc_shipvia,
       cohead_shipto_id,
       cohead_shiptoaddress1,
       cohead_shiptoaddress2,
       cohead_shiptoaddress3,
       cohead_shiptocity,
       cohead_shiptostate,
       cohead_shiptozipcode,
       cohead_shiptocountry,
       cobmisc_freight,
       cobmisc_misc,
       cobmisc_freight_taxtype_id,
       cobmisc_misc_taxtype_id,
       cobmisc_misc_discount
  FROM cobmisc
  JOIN cohead ON cobmisc_cohead_id = cohead_id
UNION ALL
SELECT 'INV',
       invchead_id,
       invchead_invcnumber,
       invchead_cust_id,
       NULL,
       invchead_curr_id,
       invchead_invcdate,
       NULL,
       NULL,
       invchead_taxzone_id,
       invchead_warehous_id,
       invchead_shipvia,
       invchead_shipto_id,
       invchead_shipto_address1,
       invchead_shipto_address2,
       invchead_shipto_address3,
       invchead_shipto_city,
       invchead_shipto_state,
       invchead_shipto_zipcode,
       invchead_shipto_country,
       invchead_freight,
       invchead_misc_amount,
       invchead_freight_taxtype_id,
       invchead_misc_taxtype_id,
       invchead_misc_discount
  FROM invchead
UNION ALL
SELECT 'P',
       pohead_id,
       pohead_number,
       NULL,
       pohead_vend_id,
       pohead_curr_id,
       pohead_orderdate,
       NULL,
       NULL,
       pohead_taxzone_id,
       pohead_warehous_id,
       pohead_shipvia,
       NULL,
       pohead_shiptoaddress1,
       pohead_shiptoaddress2,
       pohead_shiptoaddress3,
       pohead_shiptocity,
       pohead_shiptostate,
       pohead_shiptozipcode,
       pohead_shiptocountry,
       pohead_freight,
       0.0,
       pohead_freight_taxtype_id,
       NULL,
       FALSE
  FROM pohead
UNION ALL
SELECT 'VCH',
       vohead_id,
       vohead_number,
       NULL,
       vohead_vend_id,
       vohead_curr_id,
       vohead_docdate,
       NULL,
       NULL,
       vohead_taxzone_id,
       pohead_warehous_id,
       pohead_shipvia,
       NULL,
       pohead_shiptoaddress1,
       pohead_shiptoaddress2,
       pohead_shiptoaddress3,
       pohead_shiptocity,
       pohead_shiptostate,
       pohead_shiptozipcode,
       pohead_shiptocountry,
       vohead_freight,
       0.0,
       vohead_freight_taxtype_id,
       NULL,
       FALSE
  FROM vohead
  JOIN pohead ON vohead_pohead_id = pohead_id
UNION ALL
SELECT 'CM',
       cmhead_id,
       cmhead_number,
       cmhead_cust_id,
       NULL,
       cmhead_curr_id,
       cmhead_docdate,
       invchead_invcdate,
       'INV-' || invchead_invcnumber,
       cmhead_taxzone_id,
       COALESCE(invchead_warehous_id, cmhead_warehous_id),
       COALESCE(invchead_shipvia, cmhead_shipvia),
       cmhead_shipto_id,
       COALESCE(invchead_shipto_address1, cmhead_shipto_address1),
       COALESCE(invchead_shipto_address2, cmhead_shipto_address2),
       COALESCE(invchead_shipto_address3, cmhead_shipto_address3),
       COALESCE(invchead_shipto_city, cmhead_shipto_city),
       COALESCE(invchead_shipto_state, cmhead_shipto_state),
       COALESCE(invchead_shipto_zipcode, cmhead_shipto_zipcode),
       COALESCE(invchead_shipto_country, cmhead_shipto_country),
       cmhead_freight,
       cmhead_misc,
       COALESCE(invchead_freight_taxtype_id, cmhead_freight_taxtype_id),
       COALESCE(invchead_misc_taxtype_id, cmhead_misc_taxtype_id),
       cmhead_misc_discount
  FROM cmhead
  LEFT OUTER JOIN invchead ON cmhead_invcnumber = invchead_invcnumber;
